In [2]:
import pandas
df = pandas.read_csv('IK_rr_DataFrame.csv')
df

,FileName,Author,Text
0,Chaos in fractional-order discrete neural netw...,Tingwen Huang,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
1,Adaptive event-triggered control for a class o...,Tingwen Huang,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
2,Lag Synchronization of Switched Neural Network...,Tingwen Huang,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
3,Robust Exponential Stability of Uncertain Dela...,Tingwen Huang,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
4,Off-policy Reinforcement Learning.pdf,Tingwen Huang,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
...,...,...,...
640,iwann.pdf,Rama Murthy Garimella,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
641,J-(2009) - Distributed Source Coding for Senso...,Rama Murthy Garimella,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
642,InternationalConference--SimpleMedianBasedInfo...,Rama Murthy Garimella,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
643,71112_44248.pdf,Rama Murthy Garimella,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
644,JPDC_GM1_type_with_two_phases.pdf,Rama Murthy Garimella,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...

#### REMOVE KEYWORDS

In [3]:
_keyword = 'Introduction'
df['Text'] = df['Text'].str.replace(_keyword, '')

_newline_keyword = '\n'
df['Text'] = df['Text'].str.replace(_newline_keyword, '')

df.head()

,FileName,Author,Text
0,Chaos in fractional-order discrete neural netw...,Tingwen Huang,Neural Networks 125 (2020) 174–184Contents lis...
1,Adaptive event-triggered control for a class o...,Tingwen Huang,"()SCIENCE CHINAInformation SciencesMay 2020, V..."
2,Lag Synchronization of Switched Neural Network...,Tingwen Huang,untitledIEEE TRANSACTIONS ON NEURAL NETWORKS A...
3,Robust Exponential Stability of Uncertain Dela...,Tingwen Huang,"untitledSee discussions, stats, and author pro..."
4,Off-policy Reinforcement Learning.pdf,Tingwen Huang,()arXiv:1311.6107v3 [cs.SY] 11 May 2014IEEE ...

# Removing Stopwords

In [10]:
import nltk
#nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Load the stop words
stop_words = stopwords.words('english')
stop_words.extend(['@',"'",'.','"','/','!',',',"'ve","...","n't",'$',"'s",'©','''"''',"''",'..','&','*',';','”','``',':','#','!','-','–','?','%',"'d","'m",'+','++','(',')','()'])
stop_words = set(stop_words)

# Function to remove stop words from a text
def remove_stopwords(text):
    if isinstance(text, str):  # Check if the text is a string
        tokens = word_tokenize(text)
        filtered_tokens = [word for word in tokens if word.lower() not in stop_words]
        return ' '.join(filtered_tokens)
    else:
        return text


#remove_stopwords(df.loc[0,'Text'])
    
#Uncomment the next line to remove stowords from all texts. It will take some time to finish. 
#df['Text'] = df['Text'].apply(remove_stopwords)

# Print the updated DataFrame
#df.head()

0    Neural Networks 125 2020 174–184Contents lists...
1    SCIENCE CHINAInformation SciencesMay 2020 Vol ...
2    untitledIEEE TRANSACTIONS NEURAL NETWORKS LEAR...
3    untitledSee discussions stats author profiles ...
Name: Text, dtype: object

# Stemming

In [6]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

# Download the stopwords and initialize the stemmer
stop_words = stopwords.words('english')
stop_words.extend(['@',"'",'.','"','/','!',',',"'ve","...","n't",'$',"'s",'©','''"''',"''",'..','&','*',';','”','``',':','#','!','-','–','?','%',"'d","'m",'+','++','(',')','()'])
stop_words = set(stop_words)
stemmer = PorterStemmer()

# Function to remove stop words and perform stemming on a text
def preprocess_text(text):
    if isinstance(text, str):
        tokens = word_tokenize(text)
        filtered_tokens = [stemmer.stem(word.lower()) for word in tokens if word.lower() not in stop_words]
        return ' '.join(filtered_tokens)
    return text

# Apply the preprocessing function to the text column of the DataFrame
#Uncomment the next line to run. It will take some time to finish. 
#df['Text'] = df['Text'].apply(preprocess_text)

# Print the first few rows to observe the result
# df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

      Unnamed: 0                                       Introduction  \
0              0  random earli detect ( red ) algorithm becom de...
1              1  formal semant `` m. aronoff j. rees- miller ( ...
2              2  steadi increas number multi-ag system ( mass )...
3              3  steadi increas number multi-ag system ( mass )...
4              4  steadi increas number multi-ag system ( mass )...
...          ...                                                ...
5974        5974  hidden markov model wide use forstatist langua...
5975        5975                                                  3
5976        5976  concret exampl bit commit , parti , alic , wri...
5977        5977  data mine [ 3 , 5 , 7 ] develop analysi larg d...
5978        5978  paper want understand aspect behaviour addit p...

                                               Abstract  \
0     consid adapt random earli detect ( red ) activ...
1     ing away fact µ ( e ) function effect type rai...
2     describ framework equat use model predict theb...
3     describ framework equat use model predict theb...
4     describ framework equat use model predict theb...
...                                                 ...
5974  present techniqu complementshidden markov mode...
5975  one key concept test adequ test set . test sel...
5976  . known quantum bit commit would secur attacks...
5977  . discuss aspect approxim function high-dimens...
5978  . discuss aspect approxim function high-dimens...

                                           Author Names
0     'stefaan de cnodder ' , 'omar elloumi ' , 'ken...
1     'synonymi ' , 'westerståhl ' , 'zadrozni ' , '...
2                            'ma ' , 'edmund h. durfe '
3     'ma ' , 'edmund h. durfe ' , 'chavez ' , 'mae ...
4                            'ma ' , 'edmund h. durfe '
...                                                 ...
5974  'select lexicalization∗ ' , 'jin-dong kim ands...
5975                              'jan ' , 'jan pachl '
5976  'princeton ' , 'bob ' , 'alic ' , 'alic ' , 'v...
5977                                              'x1 '
5978                                       'lipschitz '

[5979 rows x 4 columns]

# Lemmatization

In [8]:
import nltk
nltk.download('omw-1.4')

import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Download the stopwords and initialize the lemmatizer
#nltk.download('stopwords')
#nltk.download('wordnet')
stop_words = stopwords.words('english')
stop_words.extend(['@',"'",'.','"','/','!',',',"'ve","...","n't",'$',"'s",'©','''"''',"''",'..','&','*',';','”','``',':','#','!','-','–','?','%',"'d","'m",'+','++','(',')','()'])
stop_words = set(stop_words)

lemmatizer = WordNetLemmatizer()

# Function to remove stop words and perform lemmatization on a text
def preprocess_text(text):
    if isinstance(text, str):
        tokens = word_tokenize(text)
        filtered_tokens = [lemmatizer.lemmatize(word.lower()) for word in tokens if word.lower() not in stop_words]
        return ' '.join(filtered_tokens)
    return text

# Apply the preprocessing function 
df['Text'] = df['Text'].apply(preprocess_text)

# Print the updated DataFrame
df.head()

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

      Unnamed: 0                                       Introduction  \
0              0  random earli detect ( red ) algorithm becom de...
1              1  formal semant `` m. aronoff j. rees- miller ( ...
2              2  steadi increas number multi-ag system ( mass )...
3              3  steadi increas number multi-ag system ( mass )...
4              4  steadi increas number multi-ag system ( mass )...
...          ...                                                ...
5974        5974  hidden markov model wide use forstatist langua...
5975        5975                                                  3
5976        5976  concret exampl bit commit , parti , alic , wri...
5977        5977  data mine [ 3 , 5 , 7 ] develop analysi larg d...
5978        5978  paper want understand aspect behaviour addit p...

                                               Abstract  \
0     consid adapt random earli detect ( red ) activ...
1     ing away fact µ ( e ) function effect type rai...
2     describ framework equat use model predict theb...
3     describ framework equat use model predict theb...
4     describ framework equat use model predict theb...
...                                                 ...
5974  present techniqu complementshidden markov mode...
5975  one key concept test adequ test set . test sel...
5976  . known quantum bit commit would secur attacks...
5977  . discus aspect approxim function high-dimensi...
5978  . discus aspect approxim function high-dimensi...

                                           Author Names
0     'stefaan de cnodder ' , 'omar elloumi ' , 'ken...
1     'synonymi ' , 'westerståhl ' , 'zadrozni ' , '...
2                            'ma ' , 'edmund h. durfe '
3     'ma ' , 'edmund h. durfe ' , 'chavez ' , 'mae ...
4                            'ma ' , 'edmund h. durfe '
...                                                 ...
5974  'select lexicalization∗ ' , 'jin-dong kim ands...
5975                              'jan ' , 'jan pachl '
5976  'princeton ' , 'bob ' , 'alic ' , 'alic ' , 'v...
5977                                              'x1 '
5978                                       'lipschitz '

[5979 rows x 4 columns]